"""add country_code / language_code to TopicDB / ScrapingSourceDB

Revision ID: 9c12b903a18e
Revises: 039cce7e2545
Create Date: 2025-08-20 14:59:20.016702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c12b903a18e'
down_revision: Union[str, Sequence[str], None] = '039cce7e2545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('scraping_sources', sa.Column('language_code', sa.String(length=2), nullable=True))
    op.alter_column('scraping_sources', 'language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_scraping_sources_country_code'), 'scraping_sources', ['country_code'], unique=False)
    op.create_index(op.f('ix_scraping_sources_language_code'), 'scraping_sources', ['language_code'], unique=False)
    op.add_column('topics', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_topics_country_code'), 'topics', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_country_code'), table_name='topics')
    op.drop_column('topics', 'country_code')
    op.drop_index(op.f('ix_scraping_sources_language_code'), table_name='scraping_sources')
    op.drop_index(op.f('ix_scraping_sources_country_code'), table_name='scraping_sources')
    op.alter_column('scraping_sources', 'language',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('scraping_sources', 'language_code')
    op.drop_column('scraping_sources', 'country_code')
    # ### end Alembic commands ###
