"""add snippet column to ExtractedEventDB

Revision ID: def7b4b8f666
Revises: 3c844a9f3938
Create Date: 2025-08-22 14:39:07.169510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def7b4b8f666'
down_revision: Union[str, Sequence[str], None] = '3c844a9f3938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_events', sa.Column('snippet', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_events', 'snippet')
    # ### end Alembic commands ###
