"""add currently_scraping to scrapingsourcedb

Revision ID: af21f44b12b4
Revises: 79fda5ffeaa7
Create Date: 2025-09-04 14:35:00.026838

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af21f44b12b4"
down_revision: Union[str, Sequence[str], None] = "79fda5ffeaa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scraping_sources", sa.Column("currently_scraping", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraping_sources", "currently_scraping")
    # ### end Alembic commands ###
