"""add is_demo_user to UserDB

Revision ID: 0dbdb441d5b7
Revises: 2a40a9e28266
Create Date: 2025-12-17 22:32:16.835696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbdb441d5b7'
down_revision: Union[str, Sequence[str], None] = '2a40a9e28266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_demo_user')
    # ### end Alembic commands ###
