"""Add CASCADE to extracted_events.event_id foreign key

Revision ID: 3c844a9f3938
Revises: 9c12b903a18e
Create Date: 2025-08-22 13:33:28.696551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c844a9f3938'
down_revision: Union[str, Sequence[str], None] = '9c12b903a18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('extracted_events_event_id_fkey'), 'extracted_events', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extracted_events', type_='foreignkey')
    op.create_foreign_key(op.f('extracted_events_event_id_fkey'), 'extracted_events', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
