"""add scraping frequency field to scraping sources

Revision ID: fe4f0caa5c1c
Revises: 56bdb2256424
Create Date: 2025-07-15 19:44:09.585069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4f0caa5c1c'
down_revision: Union[str, Sequence[str], None] = '56bdb2256424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('scraping_frequency', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_sources', 'scraping_frequency')
    # ### end Alembic commands ###
