"""add country column to Topic model

Revision ID: e2c63680af1f
Revises: 26902928785f
Create Date: 2025-07-15 09:11:13.268466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c63680af1f'
down_revision: Union[str, Sequence[str], None] = '26902928785f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('country', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'country')
    # ### end Alembic commands ###
