"""some modifications to event and extractedevent

Revision ID: d8e08bba9fc7
Revises: 13030b5007e2
Create Date: 2025-07-28 13:08:45.239156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e08bba9fc7'
down_revision: Union[str, Sequence[str], None] = '13030b5007e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_events', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'extracted_events', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extracted_events', type_='foreignkey')
    op.drop_column('extracted_events', 'topic_id')
    # ### end Alembic commands ###
