"""add cascade delete to event_comparisons foreign keys

Revision ID: a8475cf0f6f7
Revises: 1c6092c793ef
Create Date: 2025-09-04 10:03:43.132601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8475cf0f6f7'
down_revision: Union[str, Sequence[str], None] = '1c6092c793ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_comparisons_event_id_fkey'), 'event_comparisons', type_='foreignkey')
    op.drop_constraint(op.f('event_comparisons_extracted_event_id_fkey'), 'event_comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'event_comparisons', 'extracted_events', ['extracted_event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_comparisons', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_comparisons', type_='foreignkey')
    op.drop_constraint(None, 'event_comparisons', type_='foreignkey')
    op.create_foreign_key(op.f('event_comparisons_extracted_event_id_fkey'), 'event_comparisons', 'extracted_events', ['extracted_event_id'], ['id'])
    op.create_foreign_key(op.f('event_comparisons_event_id_fkey'), 'event_comparisons', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
