"""change scraping sources to belong to topics instead of users

Revision ID: fcde91f8f8e3
Revises: fe4f0caa5c1c
Create Date: 2025-07-15 19:52:18.452147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcde91f8f8e3'
down_revision: Union[str, Sequence[str], None] = 'fe4f0caa5c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('scraping_sources_user_id_fkey'), 'scraping_sources', type_='foreignkey')
    op.create_foreign_key(None, 'scraping_sources', 'topics', ['topic_id'], ['id'])
    op.drop_column('scraping_sources', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scraping_sources', type_='foreignkey')
    op.create_foreign_key(op.f('scraping_sources_user_id_fkey'), 'scraping_sources', 'users', ['user_id'], ['id'])
    op.drop_column('scraping_sources', 'topic_id')
    # ### end Alembic commands ###
