"""make event_id in ExtractedEvent nullable, ignore apscheduler and langgraph tables

Revision ID: 13030b5007e2
Revises: f3a1d693bcb2
Create Date: 2025-07-27 14:02:48.633049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13030b5007e2'
down_revision: Union[str, Sequence[str], None] = 'f3a1d693bcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extracted_events', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extracted_events', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
