"""add cascading delete behaviour to db-level instead of just sqlalchemy-level

Revision ID: 4bb1a9b15354
Revises: 0dbdb441d5b7
Create Date: 2025-12-23 15:24:26.749125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb1a9b15354'
down_revision: Union[str, Sequence[str], None] = '0dbdb441d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_topic_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('extracted_events_scraping_source_id_fkey'), 'extracted_events', type_='foreignkey')
    op.drop_constraint(op.f('extracted_events_topic_id_fkey'), 'extracted_events', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_events', 'scraping_sources', ['scraping_source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'extracted_events', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('scraping_sources_topic_id_fkey'), 'scraping_sources', type_='foreignkey')
    op.create_foreign_key(None, 'scraping_sources', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sources_topic_id_fkey'), 'sources', type_='foreignkey')
    op.drop_constraint(op.f('sources_scraping_source_id_fkey'), 'sources', type_='foreignkey')
    op.create_foreign_key(None, 'sources', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sources', 'scraping_sources', ['scraping_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('topics_user_id_fkey'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(op.f('topics_user_id_fkey'), 'topics', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.create_foreign_key(op.f('sources_scraping_source_id_fkey'), 'sources', 'scraping_sources', ['scraping_source_id'], ['id'])
    op.create_foreign_key(op.f('sources_topic_id_fkey'), 'sources', 'topics', ['topic_id'], ['id'])
    op.drop_constraint(None, 'scraping_sources', type_='foreignkey')
    op.create_foreign_key(op.f('scraping_sources_topic_id_fkey'), 'scraping_sources', 'topics', ['topic_id'], ['id'])
    op.drop_constraint(None, 'extracted_events', type_='foreignkey')
    op.drop_constraint(None, 'extracted_events', type_='foreignkey')
    op.create_foreign_key(op.f('extracted_events_topic_id_fkey'), 'extracted_events', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(op.f('extracted_events_scraping_source_id_fkey'), 'extracted_events', 'scraping_sources', ['scraping_source_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_topic_id_fkey'), 'events', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###
