"""add_ondelete_set_null_to_event_provenance_foreign_keys

Revision ID: 79fda5ffeaa7
Revises: a8475cf0f6f7
Create Date: 2025-09-04 12:34:06.435774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fda5ffeaa7'
down_revision: Union[str, Sequence[str], None] = 'a8475cf0f6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_date_from_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_description_from_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_duration_from_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_title_from_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_location_from_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'extracted_events', ['description_from_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'extracted_events', ['title_from_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'extracted_events', ['duration_from_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'extracted_events', ['location_from_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'extracted_events', ['date_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_location_from_id_fkey'), 'events', 'extracted_events', ['location_from_id'], ['id'])
    op.create_foreign_key(op.f('events_title_from_id_fkey'), 'events', 'extracted_events', ['title_from_id'], ['id'])
    op.create_foreign_key(op.f('events_duration_from_id_fkey'), 'events', 'extracted_events', ['duration_from_id'], ['id'])
    op.create_foreign_key(op.f('events_description_from_id_fkey'), 'events', 'extracted_events', ['description_from_id'], ['id'])
    op.create_foreign_key(op.f('events_date_from_id_fkey'), 'events', 'extracted_events', ['date_from_id'], ['id'])
    # ### end Alembic commands ###
