"""remove location_vector from event and extractedevent

Revision ID: 0da354497286
Revises: d8e08bba9fc7
Create Date: 2025-07-28 14:02:54.135964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da354497286'
down_revision: Union[str, Sequence[str], None] = 'd8e08bba9fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location_vector')
    op.drop_column('extracted_events', 'location_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_events', sa.Column('location_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('location_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
