"""add event_comparisons table for analysis

Revision ID: 3cbb1ae975ab
Revises: 1a6cbfffe549
Create Date: 2025-07-29 18:13:05.604766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbb1ae975ab'
down_revision: Union[str, Sequence[str], None] = '1a6cbfffe549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted_event_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('extracted_event_title', sa.String(length=500), nullable=False),
    sa.Column('extracted_event_description', sa.Text(), nullable=True),
    sa.Column('event_title', sa.String(length=500), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('vector_similarity', sa.Float(), nullable=False),
    sa.Column('vector_threshold_met', sa.Boolean(), nullable=False),
    sa.Column('llm_considers_same_event', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['extracted_event_id'], ['extracted_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_comparisons_id'), 'event_comparisons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_comparisons_id'), table_name='event_comparisons')
    op.drop_table('event_comparisons')
    # ### end Alembic commands ###
