"""change duration on event / extractedevent to timedelta/interval

Revision ID: 53ce4f38dde2
Revises: 3cbb1ae975ab
Create Date: 2025-07-30 09:13:06.681758

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53ce4f38dde2"
down_revision: Union[str, Sequence[str], None] = "3cbb1ae975ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE events ALTER COLUMN duration TYPE INTERVAL USING duration::interval")
    op.execute("ALTER TABLE extracted_events ALTER COLUMN duration TYPE INTERVAL USING duration::interval")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE extracted_events ALTER COLUMN duration TYPE VARCHAR(100) USING duration::text")
    op.execute("ALTER TABLE events ALTER COLUMN duration TYPE VARCHAR(100) USING duration::text")
    # ### end Alembic commands ###
