"""Add last_error to ScrapingSourceDB

Revision ID: 2a40a9e28266
Revises: ae4d8dd62f53
Create Date: 2025-12-12 14:55:23.427383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a40a9e28266'
down_revision: Union[str, Sequence[str], None] = 'ae4d8dd62f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_sources', 'last_error')
    # ### end Alembic commands ###
