"""Reverse event-source relationship: one event to many sources

Revision ID: 56bdb2256424
Revises: 618ee661f747
Create Date: 2025-07-15 11:57:44.989092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56bdb2256424'
down_revision: Union[str, Sequence[str], None] = '618ee661f747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sources', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event_sources', 'events', ['event_id'], ['id'])
    op.drop_constraint(op.f('events_event_source_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'event_source_id')
    op.drop_column('events', 'extracted_metadata')
    op.drop_column('events', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('extracted_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_event_source_id_fkey'), 'events', 'event_sources', ['event_source_id'], ['id'])
    op.drop_constraint(None, 'event_sources', type_='foreignkey')
    op.drop_column('event_sources', 'event_id')
    # ### end Alembic commands ###
