"""link websourcedb to scrapingsourcedb to allow cascading deletion

Revision ID: ae4d8dd62f53
Revises: af21f44b12b4
Create Date: 2025-09-11 09:20:59.064480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4d8dd62f53'
down_revision: Union[str, Sequence[str], None] = 'af21f44b12b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('scraping_source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sources', 'scraping_sources', ['scraping_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'scraping_source_id')
    # ### end Alembic commands ###
