"""add degrees_of_separation to ScrapingSource

Revision ID: 1a6cbfffe549
Revises: 0da354497286
Create Date: 2025-07-28 17:11:36.964127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6cbfffe549'
down_revision: Union[str, Sequence[str], None] = '0da354497286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('degrees_of_separation', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_sources', 'degrees_of_separation')
    # ### end Alembic commands ###
